/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iot_device.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "iot_device.pb-c.h"
void   iot_device_info__init
                     (IotDeviceInfo         *message)
{
  static const IotDeviceInfo init_value = IOT_DEVICE_INFO__INIT;
  *message = init_value;
}
size_t iot_device_info__get_packed_size
                     (const IotDeviceInfo *message)
{
  assert(message->base.descriptor == &iot_device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_device_info__pack
                     (const IotDeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_device_info__pack_to_buffer
                     (const IotDeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotDeviceInfo *
       iot_device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotDeviceInfo *)
     protobuf_c_message_unpack (&iot_device_info__descriptor,
                                allocator, len, data);
}
void   iot_device_info__free_unpacked
                     (IotDeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_value__init
                     (IotValue         *message)
{
  static const IotValue init_value = IOT_VALUE__INIT;
  *message = init_value;
}
size_t iot_value__get_packed_size
                     (const IotValue *message)
{
  assert(message->base.descriptor == &iot_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_value__pack
                     (const IotValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_value__pack_to_buffer
                     (const IotValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotValue *
       iot_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotValue *)
     protobuf_c_message_unpack (&iot_value__descriptor,
                                allocator, len, data);
}
void   iot_value__free_unpacked
                     (IotValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_attribute__params_entry__init
                     (IotAttribute__ParamsEntry         *message)
{
  static const IotAttribute__ParamsEntry init_value = IOT_ATTRIBUTE__PARAMS_ENTRY__INIT;
  *message = init_value;
}
void   iot_attribute__init
                     (IotAttribute         *message)
{
  static const IotAttribute init_value = IOT_ATTRIBUTE__INIT;
  *message = init_value;
}
size_t iot_attribute__get_packed_size
                     (const IotAttribute *message)
{
  assert(message->base.descriptor == &iot_attribute__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_attribute__pack
                     (const IotAttribute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_attribute__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_attribute__pack_to_buffer
                     (const IotAttribute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_attribute__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotAttribute *
       iot_attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotAttribute *)
     protobuf_c_message_unpack (&iot_attribute__descriptor,
                                allocator, len, data);
}
void   iot_attribute__free_unpacked
                     (IotAttribute *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_attribute__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_metadata__init
                     (IotMetadata         *message)
{
  static const IotMetadata init_value = IOT_METADATA__INIT;
  *message = init_value;
}
size_t iot_metadata__get_packed_size
                     (const IotMetadata *message)
{
  assert(message->base.descriptor == &iot_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_metadata__pack
                     (const IotMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_metadata__pack_to_buffer
                     (const IotMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotMetadata *
       iot_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotMetadata *)
     protobuf_c_message_unpack (&iot_metadata__descriptor,
                                allocator, len, data);
}
void   iot_metadata__free_unpacked
                     (IotMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_service__init
                     (IotService         *message)
{
  static const IotService init_value = IOT_SERVICE__INIT;
  *message = init_value;
}
size_t iot_service__get_packed_size
                     (const IotService *message)
{
  assert(message->base.descriptor == &iot_service__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_service__pack
                     (const IotService *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_service__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_service__pack_to_buffer
                     (const IotService *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_service__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotService *
       iot_service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotService *)
     protobuf_c_message_unpack (&iot_service__descriptor,
                                allocator, len, data);
}
void   iot_service__free_unpacked
                     (IotService *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_service__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_attribute_data__init
                     (IotAttributeData         *message)
{
  static const IotAttributeData init_value = IOT_ATTRIBUTE_DATA__INIT;
  *message = init_value;
}
size_t iot_attribute_data__get_packed_size
                     (const IotAttributeData *message)
{
  assert(message->base.descriptor == &iot_attribute_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_attribute_data__pack
                     (const IotAttributeData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_attribute_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_attribute_data__pack_to_buffer
                     (const IotAttributeData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_attribute_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotAttributeData *
       iot_attribute_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotAttributeData *)
     protobuf_c_message_unpack (&iot_attribute_data__descriptor,
                                allocator, len, data);
}
void   iot_attribute_data__free_unpacked
                     (IotAttributeData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_attribute_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_attribute_read_request__init
                     (IotAttributeReadRequest         *message)
{
  static const IotAttributeReadRequest init_value = IOT_ATTRIBUTE_READ_REQUEST__INIT;
  *message = init_value;
}
size_t iot_attribute_read_request__get_packed_size
                     (const IotAttributeReadRequest *message)
{
  assert(message->base.descriptor == &iot_attribute_read_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_attribute_read_request__pack
                     (const IotAttributeReadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_attribute_read_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_attribute_read_request__pack_to_buffer
                     (const IotAttributeReadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_attribute_read_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotAttributeReadRequest *
       iot_attribute_read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotAttributeReadRequest *)
     protobuf_c_message_unpack (&iot_attribute_read_request__descriptor,
                                allocator, len, data);
}
void   iot_attribute_read_request__free_unpacked
                     (IotAttributeReadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_attribute_read_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_attribute_write_request__init
                     (IotAttributeWriteRequest         *message)
{
  static const IotAttributeWriteRequest init_value = IOT_ATTRIBUTE_WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t iot_attribute_write_request__get_packed_size
                     (const IotAttributeWriteRequest *message)
{
  assert(message->base.descriptor == &iot_attribute_write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_attribute_write_request__pack
                     (const IotAttributeWriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_attribute_write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_attribute_write_request__pack_to_buffer
                     (const IotAttributeWriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_attribute_write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotAttributeWriteRequest *
       iot_attribute_write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotAttributeWriteRequest *)
     protobuf_c_message_unpack (&iot_attribute_write_request__descriptor,
                                allocator, len, data);
}
void   iot_attribute_write_request__free_unpacked
                     (IotAttributeWriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_attribute_write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot_attribute_response__init
                     (IotAttributeResponse         *message)
{
  static const IotAttributeResponse init_value = IOT_ATTRIBUTE_RESPONSE__INIT;
  *message = init_value;
}
size_t iot_attribute_response__get_packed_size
                     (const IotAttributeResponse *message)
{
  assert(message->base.descriptor == &iot_attribute_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_attribute_response__pack
                     (const IotAttributeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_attribute_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_attribute_response__pack_to_buffer
                     (const IotAttributeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_attribute_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotAttributeResponse *
       iot_attribute_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotAttributeResponse *)
     protobuf_c_message_unpack (&iot_attribute_response__descriptor,
                                allocator, len, data);
}
void   iot_attribute_response__free_unpacked
                     (IotAttributeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_attribute_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iot_device_info__field_descriptors[6] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotDeviceInfo, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotDeviceInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotDeviceInfo, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IotDeviceInfo, n_attributes),
    offsetof(IotDeviceInfo, attributes),
    &iot_attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IotDeviceInfo, n_services),
    offsetof(IotDeviceInfo, services),
    &iot_service__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IotDeviceInfo, metadata),
    &iot_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_device_info__field_indices_by_name[] = {
  3,   /* field[3] = attributes */
  5,   /* field[5] = metadata */
  1,   /* field[1] = name */
  4,   /* field[4] = services */
  2,   /* field[2] = type */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange iot_device_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor iot_device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotDeviceInfo",
  "IotDeviceInfo",
  "IotDeviceInfo",
  "",
  sizeof(IotDeviceInfo),
  6,
  iot_device_info__field_descriptors,
  iot_device_info__field_indices_by_name,
  1,  iot_device_info__number_ranges,
  (ProtobufCMessageInit) iot_device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_value__field_descriptors[5] =
{
  {
    "bool_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(IotValue, type_case),
    offsetof(IotValue, bool_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(IotValue, type_case),
    offsetof(IotValue, int_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(IotValue, type_case),
    offsetof(IotValue, long_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(IotValue, type_case),
    offsetof(IotValue, float_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(IotValue, type_case),
    offsetof(IotValue, string_value),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_value__field_indices_by_name[] = {
  0,   /* field[0] = bool_value */
  3,   /* field[3] = float_value */
  1,   /* field[1] = int_value */
  2,   /* field[2] = long_value */
  4,   /* field[4] = string_value */
};
static const ProtobufCIntRange iot_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor iot_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotValue",
  "IotValue",
  "IotValue",
  "",
  sizeof(IotValue),
  5,
  iot_value__field_descriptors,
  iot_value__field_indices_by_name,
  1,  iot_value__number_ranges,
  (ProtobufCMessageInit) iot_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_attribute__params_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotAttribute__ParamsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IotAttribute__ParamsEntry, value),
    &iot_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_attribute__params_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange iot_attribute__params_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor iot_attribute__params_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotAttribute.ParamsEntry",
  "ParamsEntry",
  "IotAttribute__ParamsEntry",
  "",
  sizeof(IotAttribute__ParamsEntry),
  2,
  iot_attribute__params_entry__field_descriptors,
  iot_attribute__params_entry__field_indices_by_name,
  1,  iot_attribute__params_entry__number_ranges,
  (ProtobufCMessageInit) iot_attribute__params_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_attribute__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotAttribute, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_primary",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(IotAttribute, is_primary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IotAttribute, value),
    &iot_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "params",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IotAttribute, n_params),
    offsetof(IotAttribute, params),
    &iot_attribute__params_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_attribute__field_indices_by_name[] = {
  1,   /* field[1] = is_primary */
  0,   /* field[0] = name */
  3,   /* field[3] = params */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange iot_attribute__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor iot_attribute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotAttribute",
  "IotAttribute",
  "IotAttribute",
  "",
  sizeof(IotAttribute),
  4,
  iot_attribute__field_descriptors,
  iot_attribute__field_indices_by_name,
  2,  iot_attribute__number_ranges,
  (ProtobufCMessageInit) iot_attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_metadata__field_descriptors[4] =
{
  {
    "mac_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotMetadata, mac_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotMetadata, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotMetadata, firmware_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_updated",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotMetadata, last_updated),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_metadata__field_indices_by_name[] = {
  2,   /* field[2] = firmware_version */
  3,   /* field[3] = last_updated */
  0,   /* field[0] = mac_address */
  1,   /* field[1] = model */
};
static const ProtobufCIntRange iot_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor iot_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotMetadata",
  "IotMetadata",
  "IotMetadata",
  "",
  sizeof(IotMetadata),
  4,
  iot_metadata__field_descriptors,
  iot_metadata__field_indices_by_name,
  1,  iot_metadata__number_ranges,
  (ProtobufCMessageInit) iot_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_service__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotService, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabled",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(IotService, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_core_service",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(IotService, is_core_service),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_service__field_indices_by_name[] = {
  1,   /* field[1] = enabled */
  2,   /* field[2] = is_core_service */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange iot_service__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor iot_service__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotService",
  "IotService",
  "IotService",
  "",
  sizeof(IotService),
  3,
  iot_service__field_descriptors,
  iot_service__field_indices_by_name,
  1,  iot_service__number_ranges,
  (ProtobufCMessageInit) iot_service__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_attribute_data__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotAttributeData, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IotAttributeData, value),
    &iot_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_attribute_data__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange iot_attribute_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor iot_attribute_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotAttributeData",
  "IotAttributeData",
  "IotAttributeData",
  "",
  sizeof(IotAttributeData),
  2,
  iot_attribute_data__field_descriptors,
  iot_attribute_data__field_indices_by_name,
  1,  iot_attribute_data__number_ranges,
  (ProtobufCMessageInit) iot_attribute_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_attribute_read_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(IotAttributeReadRequest, n_name),
    offsetof(IotAttributeReadRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_attribute_read_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange iot_attribute_read_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor iot_attribute_read_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotAttributeReadRequest",
  "IotAttributeReadRequest",
  "IotAttributeReadRequest",
  "",
  sizeof(IotAttributeReadRequest),
  1,
  iot_attribute_read_request__field_descriptors,
  iot_attribute_read_request__field_indices_by_name,
  1,  iot_attribute_read_request__number_ranges,
  (ProtobufCMessageInit) iot_attribute_read_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_attribute_write_request__field_descriptors[1] =
{
  {
    "attributes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IotAttributeWriteRequest, n_attributes),
    offsetof(IotAttributeWriteRequest, attributes),
    &iot_attribute_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_attribute_write_request__field_indices_by_name[] = {
  0,   /* field[0] = attributes */
};
static const ProtobufCIntRange iot_attribute_write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor iot_attribute_write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotAttributeWriteRequest",
  "IotAttributeWriteRequest",
  "IotAttributeWriteRequest",
  "",
  sizeof(IotAttributeWriteRequest),
  1,
  iot_attribute_write_request__field_descriptors,
  iot_attribute_write_request__field_indices_by_name,
  1,  iot_attribute_write_request__number_ranges,
  (ProtobufCMessageInit) iot_attribute_write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot_attribute_response__field_descriptors[1] =
{
  {
    "attributes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(IotAttributeResponse, n_attributes),
    offsetof(IotAttributeResponse, attributes),
    &iot_attribute_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_attribute_response__field_indices_by_name[] = {
  0,   /* field[0] = attributes */
};
static const ProtobufCIntRange iot_attribute_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor iot_attribute_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotAttributeResponse",
  "IotAttributeResponse",
  "IotAttributeResponse",
  "",
  sizeof(IotAttributeResponse),
  1,
  iot_attribute_response__field_descriptors,
  iot_attribute_response__field_indices_by_name,
  1,  iot_attribute_response__number_ranges,
  (ProtobufCMessageInit) iot_attribute_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue iot_value_type__enum_values_by_number[6] =
{
  { "IOT_VAL_TYPE_BOOLEAN", "IOT_VALUE_TYPE__IOT_VAL_TYPE_BOOLEAN", 0 },
  { "IOT_VAL_TYPE_INTEGER", "IOT_VALUE_TYPE__IOT_VAL_TYPE_INTEGER", 1 },
  { "IOT_VAL_TYPE_FLOAT", "IOT_VALUE_TYPE__IOT_VAL_TYPE_FLOAT", 2 },
  { "IOT_VAL_TYPE_LONG", "IOT_VALUE_TYPE__IOT_VAL_TYPE_LONG", 3 },
  { "IOT_VAL_TYPE_STRING", "IOT_VALUE_TYPE__IOT_VAL_TYPE_STRING", 4 },
  { "IOT_VAL_TYPE_UNKNOWN", "IOT_VALUE_TYPE__IOT_VAL_TYPE_UNKNOWN", 5 },
};
static const ProtobufCIntRange iot_value_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex iot_value_type__enum_values_by_name[6] =
{
  { "IOT_VAL_TYPE_BOOLEAN", 0 },
  { "IOT_VAL_TYPE_FLOAT", 2 },
  { "IOT_VAL_TYPE_INTEGER", 1 },
  { "IOT_VAL_TYPE_LONG", 3 },
  { "IOT_VAL_TYPE_STRING", 4 },
  { "IOT_VAL_TYPE_UNKNOWN", 5 },
};
const ProtobufCEnumDescriptor iot_value_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IotValueType",
  "IotValueType",
  "IotValueType",
  "",
  6,
  iot_value_type__enum_values_by_number,
  6,
  iot_value_type__enum_values_by_name,
  1,
  iot_value_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
