/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iot_ota.proto */

#ifndef PROTOBUF_C_iot_5fota_2eproto__INCLUDED
#define PROTOBUF_C_iot_5fota_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "iot_common.pb-c.h"

typedef struct _IotOtaStatusResponse IotOtaStatusResponse;


/* --- enums --- */


/* --- messages --- */

/*
 ** A response message of an ota update status response. 
 */
struct  _IotOtaStatusResponse
{
  ProtobufCMessage base;
  /*
   **< The status of the update. 
   */
  IotResponseStatus status;
  /*
   **< The compile time of the update. 
   */
  char *compile_time;
  /*
   **< The compile date of the update. 
   */
  char *compile_date;
  /*
   **< The version of the update. 
   */
  char *version;
};
#define IOT_OTA_STATUS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot_ota_status_response__descriptor) \
    , IOT_RESPONSE_STATUS__SUCCESS, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* IotOtaStatusResponse methods */
void   iot_ota_status_response__init
                     (IotOtaStatusResponse         *message);
size_t iot_ota_status_response__get_packed_size
                     (const IotOtaStatusResponse   *message);
size_t iot_ota_status_response__pack
                     (const IotOtaStatusResponse   *message,
                      uint8_t             *out);
size_t iot_ota_status_response__pack_to_buffer
                     (const IotOtaStatusResponse   *message,
                      ProtobufCBuffer     *buffer);
IotOtaStatusResponse *
       iot_ota_status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot_ota_status_response__free_unpacked
                     (IotOtaStatusResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IotOtaStatusResponse_Closure)
                 (const IotOtaStatusResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor iot_ota_status_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_iot_5fota_2eproto__INCLUDED */
