/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iot_ota.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "iot_ota.pb-c.h"
void   iot_ota_status_response__init
                     (IotOtaStatusResponse         *message)
{
  static const IotOtaStatusResponse init_value = IOT_OTA_STATUS_RESPONSE__INIT;
  *message = init_value;
}
size_t iot_ota_status_response__get_packed_size
                     (const IotOtaStatusResponse *message)
{
  assert(message->base.descriptor == &iot_ota_status_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_ota_status_response__pack
                     (const IotOtaStatusResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_ota_status_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_ota_status_response__pack_to_buffer
                     (const IotOtaStatusResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_ota_status_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotOtaStatusResponse *
       iot_ota_status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotOtaStatusResponse *)
     protobuf_c_message_unpack (&iot_ota_status_response__descriptor,
                                allocator, len, data);
}
void   iot_ota_status_response__free_unpacked
                     (IotOtaStatusResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_ota_status_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iot_ota_status_response__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IotOtaStatusResponse, status),
    &iot_response_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compile_time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotOtaStatusResponse, compile_time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compile_date",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotOtaStatusResponse, compile_date),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotOtaStatusResponse, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_ota_status_response__field_indices_by_name[] = {
  2,   /* field[2] = compile_date */
  1,   /* field[1] = compile_time */
  0,   /* field[0] = status */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange iot_ota_status_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor iot_ota_status_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotOtaStatusResponse",
  "IotOtaStatusResponse",
  "IotOtaStatusResponse",
  "",
  sizeof(IotOtaStatusResponse),
  4,
  iot_ota_status_response__field_descriptors,
  iot_ota_status_response__field_indices_by_name,
  1,  iot_ota_status_response__number_ranges,
  (ProtobufCMessageInit) iot_ota_status_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
