/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iot_provision.proto */

#ifndef PROTOBUF_C_iot_5fprovision_2eproto__INCLUDED
#define PROTOBUF_C_iot_5fprovision_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _IotProvisionRequest IotProvisionRequest;
typedef struct _IotProvisionResponse IotProvisionResponse;


/* --- enums --- */

/*
 * An enum of the different provisioning statuses
 */
typedef enum _IotProvisionStatus {
  /*
   * The provisioning was successful
   */
  IOT_PROVISION_STATUS__Success = 0,
  /*
   * The provisioning failed due to an invalid argument
   */
  IOT_PROVISION_STATUS__InvalidArgument = 1,
  /*
   * The provisioning failed due to an internal error during processing
   */
  IOT_PROVISION_STATUS__InternalError = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT_PROVISION_STATUS)
} IotProvisionStatus;

/* --- messages --- */

/*
 * A request message for provisioning a device
 */
struct  _IotProvisionRequest
{
  ProtobufCMessage base;
  /*
   * The hover server's URL
   */
  char *server_url;
  /*
   * The devices name
   */
  char *device_name;
  /*
   * The device's uuid
   */
  char *device_uuid;
  /*
   * The device timezone
   */
  char *timezone;
};
#define IOT_PROVISION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot_provision_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * A response message of provisioning a device
 */
struct  _IotProvisionResponse
{
  ProtobufCMessage base;
  /*
   * The response status
   */
  IotProvisionStatus status;
  /*
   * The response message
   */
  char *message;
};
#define IOT_PROVISION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot_provision_response__descriptor) \
    , IOT_PROVISION_STATUS__Success, (char *)protobuf_c_empty_string }


/* IotProvisionRequest methods */
void   iot_provision_request__init
                     (IotProvisionRequest         *message);
size_t iot_provision_request__get_packed_size
                     (const IotProvisionRequest   *message);
size_t iot_provision_request__pack
                     (const IotProvisionRequest   *message,
                      uint8_t             *out);
size_t iot_provision_request__pack_to_buffer
                     (const IotProvisionRequest   *message,
                      ProtobufCBuffer     *buffer);
IotProvisionRequest *
       iot_provision_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot_provision_request__free_unpacked
                     (IotProvisionRequest *message,
                      ProtobufCAllocator *allocator);
/* IotProvisionResponse methods */
void   iot_provision_response__init
                     (IotProvisionResponse         *message);
size_t iot_provision_response__get_packed_size
                     (const IotProvisionResponse   *message);
size_t iot_provision_response__pack
                     (const IotProvisionResponse   *message,
                      uint8_t             *out);
size_t iot_provision_response__pack_to_buffer
                     (const IotProvisionResponse   *message,
                      ProtobufCBuffer     *buffer);
IotProvisionResponse *
       iot_provision_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot_provision_response__free_unpacked
                     (IotProvisionResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IotProvisionRequest_Closure)
                 (const IotProvisionRequest *message,
                  void *closure_data);
typedef void (*IotProvisionResponse_Closure)
                 (const IotProvisionResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    iot_provision_status__descriptor;
extern const ProtobufCMessageDescriptor iot_provision_request__descriptor;
extern const ProtobufCMessageDescriptor iot_provision_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_iot_5fprovision_2eproto__INCLUDED */
