/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iot_common.proto */

#ifndef PROTOBUF_C_iot_5fcommon_2eproto__INCLUDED
#define PROTOBUF_C_iot_5fcommon_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _IotResponse IotResponse;


/* --- enums --- */

/*
 ** An enum of the different types of repose status. 
 */
typedef enum _IotResponseStatus {
  /*
   **< Indicates the request was successful. 
   */
  IOT_RESPONSE_STATUS__SUCCESS = 0,
  /*
   **< Indicates the request failed due to an error. 
   */
  IOT_RESPONSE_STATUS__FAILED = 1,
  /*
   **< Indicates the request was rejected possibly due to invalid input or permissions. 
   */
  IOT_RESPONSE_STATUS__REJECTED = 2,
  /*
   **< Indicates the request failed due to insufficient memory. 
   */
  IOT_RESPONSE_STATUS__NO_MEMORY = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT_RESPONSE_STATUS)
} IotResponseStatus;

/* --- messages --- */

/*
 ** A common message that represents a response from an operation. 
 */
struct  _IotResponse
{
  ProtobufCMessage base;
  /*
   **< The status of the response. 
   */
  IotResponseStatus status;
  /*
   **< The message providing additional details about the response. 
   */
  char *message;
};
#define IOT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot_response__descriptor) \
    , IOT_RESPONSE_STATUS__SUCCESS, (char *)protobuf_c_empty_string }


/* IotResponse methods */
void   iot_response__init
                     (IotResponse         *message);
size_t iot_response__get_packed_size
                     (const IotResponse   *message);
size_t iot_response__pack
                     (const IotResponse   *message,
                      uint8_t             *out);
size_t iot_response__pack_to_buffer
                     (const IotResponse   *message,
                      ProtobufCBuffer     *buffer);
IotResponse *
       iot_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot_response__free_unpacked
                     (IotResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IotResponse_Closure)
                 (const IotResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    iot_response_status__descriptor;
extern const ProtobufCMessageDescriptor iot_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_iot_5fcommon_2eproto__INCLUDED */
