/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: iot_common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "iot_common.pb-c.h"
void   iot_response__init
                     (IotResponse         *message)
{
  static const IotResponse init_value = IOT_RESPONSE__INIT;
  *message = init_value;
}
size_t iot_response__get_packed_size
                     (const IotResponse *message)
{
  assert(message->base.descriptor == &iot_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot_response__pack
                     (const IotResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot_response__pack_to_buffer
                     (const IotResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IotResponse *
       iot_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IotResponse *)
     protobuf_c_message_unpack (&iot_response__descriptor,
                                allocator, len, data);
}
void   iot_response__free_unpacked
                     (IotResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iot_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IotResponse, status),
    &iot_response_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IotResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot_response__field_indices_by_name[] = {
  1,   /* field[1] = message */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange iot_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor iot_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IotResponse",
  "IotResponse",
  "IotResponse",
  "",
  sizeof(IotResponse),
  2,
  iot_response__field_descriptors,
  iot_response__field_indices_by_name,
  1,  iot_response__number_ranges,
  (ProtobufCMessageInit) iot_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue iot_response_status__enum_values_by_number[4] =
{
  { "SUCCESS", "IOT_RESPONSE_STATUS__SUCCESS", 0 },
  { "FAILED", "IOT_RESPONSE_STATUS__FAILED", 1 },
  { "REJECTED", "IOT_RESPONSE_STATUS__REJECTED", 2 },
  { "NO_MEMORY", "IOT_RESPONSE_STATUS__NO_MEMORY", 3 },
};
static const ProtobufCIntRange iot_response_status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex iot_response_status__enum_values_by_name[4] =
{
  { "FAILED", 1 },
  { "NO_MEMORY", 3 },
  { "REJECTED", 2 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor iot_response_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IotResponseStatus",
  "IotResponseStatus",
  "IotResponseStatus",
  "",
  4,
  iot_response_status__enum_values_by_number,
  4,
  iot_response_status__enum_values_by_name,
  1,
  iot_response_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
